CREATE TABLE usuarios(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	correo VARCHAR(150) NOT NULL unique KEY,
	PASSWORD VARCHAR(150) NOT null
	
)
ALTER TABLE usuario ADD Rut varchar (15) UNIQUE NOT null;